import * as SecureStore from 'expo-secure-store';
import Constants from 'expo-constants';
import { Alert } from 'react-native';
import { emitSessionExpired } from './auth-events';

export const API_BASE_URL = Constants.expoConfig?.extra?.API_BASE_URL || 'http://localhost:3000';

/**
 * A wrapper around native `fetch` that automatically injects the JWT token
 * from `expo-secure-store` into the `Authorization` header.
 */
export async function fetchWithAuth(endpoint: string, options: RequestInit = {}) {
    // Retrieve token
    const token = await SecureStore.getItemAsync('auth_token');

    // Prepare headers
    const headers = new Headers(options.headers || {});
    headers.set('Content-Type', 'application/json');

    if (token) {
        headers.set('Authorization', `Bearer ${token}`);
    }

    // Ensure endpoint starts with slash if not provided
    const formattedEndpoint = endpoint.startsWith('/') ? endpoint : `/${endpoint}`;

    try {
        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 30000); // 30 s timeout

        console.log(`[API] ${(options.method || 'GET').toUpperCase()} ${API_BASE_URL}${formattedEndpoint}`);

        const response = await fetch(`${API_BASE_URL}${formattedEndpoint}`, {
            ...options,
            headers,
            signal: controller.signal as any, // RN AbortSignal type compat
        });
        clearTimeout(timeoutId);

        console.log(`[API] ← ${response.status} ${response.statusText}`);

        // A 401 means the JWT is invalid/expired — sign the user out automatically
        if (response.status === 401) {
            emitSessionExpired();
        }
        return response;
    } catch (error: any) {
        if (error.name === 'AbortError') {
            console.warn(`[API] Request timed out: ${formattedEndpoint}`);
            Alert.alert('Request Timeout', 'The server took too long to respond. Please try again.');
            throw new Error('Request timed out');
        }
        // Intercept raw "Network request failed" TypeErrors locally generated by Expo
        if (error.message && error.message.toLowerCase().includes('network request failed')) {
            console.error(`[API] Network error: ${error.message}`);
            Alert.alert("Connection Offline", "Cannot reach the Pristine server. Please check your internet connection or try again later.");
            throw new Error("Local Network Error: Backend Offline");
        }
        throw error;
    }
}
